on:
    push: 
        branches:
            - main 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Log in to Docker Hub
              uses: docker/login-action@v3  
              with: 
                username: priyankagupta2403
                password: vvpna9598
            - name: Build and push Docker image
              uses: docker/build-push-action@v5  
              with:
                context: .
                push: true
                tags: ${{secrets.DOCKER_USER_NAME}}/bankhub
            - name: Log Out of Dockerhub 
              run: docker logout  
    deploy:
        needs: build
        runs-on: self-hosted

        steps:
          - name: Check out
            uses: actions/checkout@v4
          - name: back to root folder
            run: cd 
          - name: deleting everything
            run: docker compose down
          - name: free up memory
            run: |
             docker rmi -f teamdualite/ai-server 
             docker rmi -f nginx    
          - name: pull fresh image
            run: docker compose pull 
          - name: running again
            run: docker compose up --remove-orphans -d              
        



