on:
    push: 
        branches:
            - main 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Log in to Docker Hub
              uses: docker/login-action@v3  
              with: 
                username: ${{ secrets.Docker_User_Name}}  
                password: ${{ secrets.DOCKER_User_Password}}
            - name: Build and push Docker image
              uses: docker/build-push-action@v5  
              with:
                context: .
                push: true
                tags: ${{secrets.Docker_User_Name}}/bankhub
            - name: Log Out of Dockerhub 
              run: docker logout    

